### ISSUE TITLE
Invalid host

### ISSUE THREAD

**Issue by juhakivekas** [AresS31/swurg#3]
When sending a request to Repeater, there is an exception happening. This issue is present in the jar in commit `935eb02`. Similar exceptions are encountered when:

- sending to Active scanner and Intruder
- with and without the `http://` prefix
- with and without the `/somepath` postfix

Here's a stacktrace of the error:

```
java.lang.IllegalArgumentException: Invalid host: http://some.random.host:8080/somepath
	at burp.bd.sendToRepeater(Unknown Source)
	at burp.ContextMenu$3.actionPerformed(ContextMenu.java:69)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by AresS31** [comment]
Thank you for your feedback @juhakivekas.

I am very busy at thye moment, I will have to time to take a look at this issue only next week. 

I saw your merge request, which I approuved.

Did it fix this issue?

**Comment by juhakivekas** [comment]
I can't verify at the moment because the code doesn't compile on my debian with up to date default-jre from apt repositories. I'll try to get the code to compile and I'll let you know as soon as I do. At the moment I'm still getting six errors, but I'll be working on this code about an hour every morning this week.

**Comment by juhakivekas** [comment]
In Burps extender the host and port for `sendToRepeater` are passed in separate variables. The host `some.random.host:8080` is a valid host according to the swagger [specification](http://swagger.io/specification/), but not as a host in the Burp extender. This is the reason for the exception, and it seems this is just a use-case that hasn't been taken into account.

Swurg already guesses the port number based on the `schemes`  field in the swagger file. In order to enable connecting to APIs not on the schemes default ports, the `host` parameter should first be checked for a port number, and if one is found, then this should be used instead of the value returned by `protocolToPort(protocol)`.

**Comment by AresS31** [comment]
This solution is now implemented, an update will soon released.
