### ISSUE TITLE
[BUG] OpenAPI Spec Failing to Parse

### ISSUE THREAD

**Issue by theemanofsteele** [aress31/swurg#98]
# Prerequisites Checklist

Before submitting the issue, please make sure you have:

- [x] Thoroughly read the [README file](https://github.com/aress31/swurg/blob/main/README.md).
- [x] Checked the [project requirements](https://github.com/aress31/swurg#requirements) and ensured they are met.
- [x] Searched for existing issues that may address the problem.
- [x] Performed basic troubleshooting steps.

# Description
It appears there is a failure during the parsing of the OpenAPI spec. I've tried using the hosted spec, YAML, and JSON formats. All return the same error. 

I've also compiled the latest version of _this_ repo and NOT using the BApp store extension. 
I removed any OpenAPI extensions and restarted BSP and then manually loaded this extension.

# Steps to Reproduce

1. Go to OpenAPI Parser Extension
2. Click on Browse to the YAML/JSON files (or paste in the endpoint for the hosted spec)
3. Click on Load
4. See error at the bottom of BSP
5. Check the error log in the Extensions tab

# Expected Behavior
I would expect to see the extension load our API Spec the same as it does a common spec like https://petstore.swagger.io/v2/swagger.json

I've tested it with the above spec and everything loads fine.

# Environment

- OS: MacOS
- Java version: 17
- Gradle version: 7.4.2
- Burp Suite version: Professional 2023.4.3
- Swurg version: Latest on Main

# OpenAPI Specification

- OpenAPI version: 3.0.1
- Sample specification snippet (if applicable):
Happy to share in a DM

# Error Message

All 3 formats of the spec result in the follow error:
```
java.lang.NullPointerException: Cannot read the array length because "<parameter4>" is null
	at burp.Zjtf.ZU(Unknown Source)
	at burp.Zjtf.Zy(Unknown Source)
	at burp.Znk.ZV(Unknown Source)
	at burp.Zvtt.ZX(Unknown Source)
	at burp.Zp98.ZX(Unknown Source)
	at burp.Zqk1.ZV(Unknown Source)
	at burp.Zq9u.ZI(Unknown Source)
	at burp.Zh64.ZF(Unknown Source)
	at burp.Zioj.withAddedParameters(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zqs.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy48.withAddedParameters(Unknown Source)
	at swurg.workers.Worker.lambda$parseOpenAPI$1(Worker.java:110)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at swurg.workers.Worker.parseOpenAPI(Worker.java:85)
	at swurg.gui.views.ParserPanel$LoadButtonListener.actionPerformed(ParserPanel.java:172)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Cannot read the array length because "<parameter4>" is null
```

# Additional Context

One thing I would like to add:
I have ran our API Spec through https://editor.swagger.io/ and have confirmed there are no spec errors that it is showing. 
If there is an error with out spec, the Swagger Editor and Linters aren't picking it up.

**Comment by waelayoub** [comment]
Hello, did you find any solution for the problem? I am facing the same problem and i still could not find a work around.

**Comment by lNATl** [comment]
I have the same problem. Please fix the problem.

**Comment by aress31** [comment]
@theemanofsteele it works fine for me, see below.

![image](https://github.com/aress31/swurg/assets/11601622/057418e3-7f4d-43e6-9c95-6f4e296efb30)

Try to compile and run the project on this repo and reopen the ticket if your error persists.

**Comment by JasperSurmont** [comment]
> @theemanofsteele it works fine for me, see below.

I'd like to add that this issue is not fixed yet, I have the same problem. What @theemanofsteele said is that the provided spec (the one you tested) indeed works, but his custom spec doesn't. 

I tried with my custom spec using a freshly compiled version from this repoand got the exact same error message. My spec is valid in swagger-ui, and the error messages do not add any information on where the spec supposedly is wrong.

**Comment by theemanofsteele** [comment]
Sorry for the delayed response. I should have been updating sooner. 

So we are still seeing this issue. However. I don't know that I feel justified to reopen it. I'll explain. 

What we have discovered is that our API Spec files are _almost_ correct. We've been using Swagger Editor and other linters to "validate" the API spec. On the surface, it seems that everything is OK. It would seem a lot of tools are fairly "forgiving" when it comes to processing/parsing a OAS file. This particular Burp extension however, is not so forgiving. For example, we had a section in one of our specs that looked similar to this (paraphrased)...
```
paths:
  /foo/bar/v1/data:
    get:
      summary: Get data
      tags:
        - data
      security:
        - bearer: []
      parameters:
        - name: data
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/data"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/dataResponse"
```
If you were to check this against the Swagger Editor, it would give it a "pass". But the Burp extension didn't like that. This is where we'd see the `parameter4` null error. So after some trouble shooting we discovered what it was complaining about. The OAS documentation has an example on a typical paths object: https://swagger.io/specification/v3/#paths-object. Specifically, we needed to our parameter to look like this:
```
schema:
  type: array
  items:
    $ref: "#/components/schemas/data"
```

Once we changed our specs to follow that pattern, we'd get past that error. There have been some other smaller similar issues but once we discovered this, we've been able to troubleshoot our own specs and have been able to get the Burp extension to accept our OAS files. 

It's not ideal but I don't necessarily hold @aress31 at fault here. The extension parses successfully once we have the spec formatted right. It's just tough to know exactly what it wants. The error messages are no where near helpful. And at the same time, Swagger Editor and other linters are telling us our OAS files are good when in reality, they do have faults that should be caught. 

Hopefully that is helpful for those following along. 
RE: @JasperSurmont

**Comment by xopherKPMG** [comment]
I am also experiencing this issue and am disappointed that a proper solution has not been provided. It would take way too long to go through the YAML file and reformat it to be 'just right' based on the parser's overly strict standards.

**Comment by siloed** [comment]
> Sorry for the delayed response. I should have been updating sooner.
> 
> So we are still seeing this issue. However. I don't know that I feel justified to reopen it. I'll explain.
> 
> What we have discovered is that our API Spec files are _almost_ correct. We've been using Swagger Editor and other linters to "validate" the API spec. On the surface, it seems that everything is OK. It would seem a lot of tools are fairly "forgiving" when it comes to processing/parsing a OAS file. This particular Burp extension however, is not so forgiving. For example, we had a section in one of our specs that looked similar to this (paraphrased)...
> 
> ```
> paths:
>   /foo/bar/v1/data:
>     get:
>       summary: Get data
>       tags:
>         - data
>       security:
>         - bearer: []
>       parameters:
>         - name: data
>           in: query
>           required: false
>           schema:
>             $ref: "#/components/schemas/data"
>       responses:
>         200:
>           description: OK
>           content:
>             application/json:
>               schema:
>                 $ref: "#/components/schemas/dataResponse"
> ```
> 
> If you were to check this against the Swagger Editor, it would give it a "pass". But the Burp extension didn't like that. This is where we'd see the `parameter4` null error. So after some trouble shooting we discovered what it was complaining about. The OAS documentation has an example on a typical paths object: https://swagger.io/specification/v3/#paths-object. Specifically, we needed to our parameter to look like this:
> 
> ```
> schema:
>   type: array
>   items:
>     $ref: "#/components/schemas/data"
> ```
> 
> Once we changed our specs to follow that pattern, we'd get past that error. There have been some other smaller similar issues but once we discovered this, we've been able to troubleshoot our own specs and have been able to get the Burp extension to accept our OAS files.
> 

Here's a python Script that can do that. I did it with a swagger.json file, you can modify it for yaml etc as needed.
```python
import json

def replace_schema_refs(obj):
    """
    Recursively traverse the JSON object and replace specific "schema" instances.
    """
    if isinstance(obj, dict):
        new_obj = {}
        for k, v in obj.items():
            if k == 'schema' and isinstance(v, dict) and v.keys() == {'$ref'}:
                # Perform the replacement
                new_obj[k] = {
                    "type": "array",
                    "items": {
                        "$ref": v["$ref"]
                    }
                }
            else:
                # Recursively process the value
                new_obj[k] = replace_schema_refs(v)
        return new_obj
    elif isinstance(obj, list):
        # Process each item in the list
        return [replace_schema_refs(item) for item in obj]
    else:
        # Return the value if it's neither a dict nor a list
        return obj

def main():
    # Load the original swagger.json file
    with open('swagger.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Perform the replacements
    updated_data = replace_schema_refs(data)

    # Write the modified data to a new file
    with open('swagger_modified.json', 'w', encoding='utf-8') as f:
        json.dump(updated_data, f, indent=2)

    print("Replacement complete. Modified file saved as 'swagger_modified.json'.")

if __name__ == '__main__':
    main()
```

Save it and run it as python3 .\converter.py swagger.json

Basically it replaces areas in your swagger.json that has path objects like this:
```json
"schema": { 
  "$ref": "#/components/schemas/SomeModel"
}
```

..with this instead to match with this burp plugin as it works at the moment of writing this:
```json
"schema": {
  "type": "array",
  "items": {
    "$ref": "#/components/schemas/SomeModel"
  }
}

```

Hope this helps anyone else that struggled with this as I did.
